'use strict';
/* ==========================================================================
   MODULES — 65 tabs. Technical modules follow the standard A–V structure.
   ========================================================================== */
const GROUPS = ['Project','Site & Survey','Geotechnical & Earthworks','Hydrology & Drainage (MSMA)','Roads & Access','Foundations & Structures','Cable, Services & Ancillary','BESS Civil','Construction','Commercial & Tender','Risk & Compliance','Registers & Deliverables','Report'];

const MODULES = [
 {id:'m1', no:1, name:'Dashboard', grp:'Project', kind:'dash'},
 {id:'m2', no:2, name:'Project Information', grp:'Project', kind:'info'},
 {id:'m3', no:3, name:'Project Coordinates', grp:'Project', kind:'coords'},
 {id:'m4', no:4, name:'Site Location', grp:'Project', kind:'location'},
 {id:'m5', no:5, name:'Documents', grp:'Project', kind:'docs'},
 {id:'m6', no:6, name:'C&S Tender Checklist', grp:'Project', kind:'checklist'},
 {id:'m7', no:7, name:'Site Assessment', grp:'Site & Survey', tech:true, calcs:[], custom:'site',
  ov:'Screening of site constraints (access, topography, hydrology, geotechnics, utilities, environment, land) with a weighted constraint rating that feeds the risk register and design basis.',
  avail:['Site visit record','Topographical survey','SI factual report','Land title'], crit:['Constraint rating: Low = 1, Moderate = 2, High = 3; overall = weighted mean'], out:['Utility search (TNB, Telekom, water) not yet received'], rec:['Carry out joint site walk with EPC and client before tender close.']},
 {id:'m8', no:8, name:'Topographical Assessment', grp:'Site & Survey', tech:true, calcs:['TOPO'], custom:'topo',
  ov:'Elevation and slope statistics from the DTM, slope band distribution and developable area; suitability ratings for grading, drainage, foundations and access.',
  avail:['Topographical survey / DTM (GDM2000)'], out:['Surveyed DTM of adequate density (≤ 25 m grid) for detailed earthworks'], rec:['Obtain full DTM with spot levels at 25 m grid, breaklines along drains and boundary.']},
 {id:'m9', no:9, name:'Land / Boundary', grp:'Site & Survey', tech:true, calcs:['LAND'], custom:'lots',
  ov:'Reconciliation of lot areas with the project land area and determination of net developable land after setbacks and reserves.',
  avail:['Title / lot plans'], out:['Certified title search for pending lots','PBT setback requirement'], rec:['Confirm setbacks with PBT and river reserve with JPS before layout freeze.']},
 {id:'m10', no:10, name:'Geotechnical Assessment', grp:'Geotechnical & Earthworks', tech:true, calcs:['GEO'], custom:'bh',
  ov:'Borehole data management, graphical soil profiles, engineering parameter interpretation (measured vs interpreted vs assumed) and identification of governing ground conditions.',
  avail:['SI factual report','Laboratory results'], out:['Laboratory strength tests','Additional boreholes / CPT for 1 BH per 25 ha','Pile driving trial records'], rec:['Supplementary SI focused on array blocks with soft clay and on substation/BESS platforms.']},
 {id:'m11', no:11, name:'Earthworks', grp:'Geotechnical & Earthworks', tech:true, calcs:['EWB'],
  ov:'Earthwork quantities for stripping, unsuitable removal, cut, fill, import, disposal and haulage, derived from the cut & fill and grading calculations.',
  avail:['DTM','Test pits (topsoil / unsuitable thickness)'], out:['Test pit logs for topsoil and unsuitable depth','Borrow source'], rec:['Carry out compaction trials to confirm shrinkage factor.'],
  sens:[{calc:'EWB', key:'tu', vals:[0.2,0.4,0.6,0.8,1.0,1.2], out:[['importV','Imported fill (m³)'],['disposal','Disposal (m³)']], xl:'Unsuitable thickness t_u (m)', yl:'Volume (m³)'}]},
 {id:'m12', no:12, name:'Grading', grp:'Geotechnical & Earthworks', tech:true, calcs:['GRD'], custom:'grading',
  ov:'Grading zones (none / moderate / major) against tracker or fixed-tilt slope tolerances, and array grading volume.',
  avail:['DTM','Tracker vendor slope tolerances'], out:['Vendor N–S / E–W slope tolerance letter'], rec:['Align tracker rows with contours in moderate zones to avoid grading.'],
  sens:[{calc:'GRD', key:'sNS', vals:[4,6,8,10,12,15], out:[['gradeV','Grading volume (m³)']], xl:'N–S tolerance (%)', yl:'Volume (m³)'}]},
 {id:'m13', no:13, name:'Cut & Fill', grp:'Geotechnical & Earthworks', tech:true, calcs:['CF'], custom:'platforms',
  ov:'Grid-method cut & fill for platforms and array grading with bulking/shrinkage adjustment and preliminary earthworks cost.',
  avail:['DTM','Platform layout'], out:['Final platform levels (after flood level confirmation)'], rec:['Balance earthworks by adjusting platform levels within flood constraints.'],
  sens:[{calc:'CF', key:'sf', vals:[0.80,0.85,0.90,0.95,1.00], out:[['net','Net balance (m³)']], xl:'Shrinkage factor', yl:'Net balance (m³)'}]},
 {id:'m14', no:14, name:'Slope Engineering', grp:'Geotechnical & Earthworks', tech:true, calcs:['SLP'],
  ov:'Screening of cut / fill slope stability for platforms, pond embankments and road cuttings.',
  avail:['Slope geometry','Soil parameters'], out:['Shear strength tests on fill / cut material'], rec:['Detailed LEM analysis for slopes > 6 m or FS < 1.5.'],
  sens:[{calc:'SLP', key:'b', vals:[18,21.8,26.6,30,33.7,38], out:[['fs','Governing FS']], xl:'Slope angle β (°)', yl:'FS', hl:(R)=>({y:R.SLP.I.FSreq, label:'FS required'})}]},
 {id:'m15', no:15, name:'Hydrology', grp:'Hydrology & Drainage (MSMA)', tech:true, calcs:['IDF','CAT','TC','RAT'], custom:'hydro', conflict:true,
  ov:'MSMA-based hydrology: IDF rainfall, catchment and sub-catchment analysis, time of concentration, Rational Method peak flows and pre- vs post-development comparison.',
  avail:['Catchment plan','JPS IDF data'], out:['Official IDF coefficients (JPS)','External catchment confirmation'], rec:['Request JPS IDF station data and confirm design ARIs with JPS/PBT.'],
  sens:[{calc:'RAT', key:'Tdet', vals:[2,5,10,20,50,100], out:[['Qpre','Q pre (m³/s)'],['Qpost','Q post (m³/s)']], xl:'ARI (years)', yl:'Design discharge (m³/s)'}]},
 {id:'m16', no:16, name:'Drainage', grp:'Hydrology & Drainage (MSMA)', tech:true, calcs:['MAN','DSZ','OUT','QDRN'],
  ov:'Open drain conveyance check (Manning), auto-sizing, velocity checks and outfall analysis; drainage quantities.',
  avail:['Drainage layout','Outfall survey'], out:['Outfall survey & downstream capacity','Receiving water tailwater level'], rec:['Adopt auto-sized concrete-lined section on steep collector drains; retain earth drains only where V ≤ 1.0 m/s.'],
  sens:[{calc:'MAN', key:'b', vals:[0.6,0.9,1.2,1.5,1.8,2.1,2.4], out:[['Qcap','Drain capacity (m³/s)']], xl:'Base width b (m)', yl:'Capacity (m³/s)', hl:(R)=>({y:R.MAN.I.Q, label:'Q design'})}]},
 {id:'m17', no:17, name:'Culvert', grp:'Hydrology & Drainage (MSMA)', tech:true, calcs:['CUL','SCR'],
  ov:'Culvert barrel capacity and headwater under inlet / outlet control with auto-sizing, and outlet scour protection.',
  avail:['Road crossing layout'], out:['Crossing invert survey'], rec:['Standardise crossings to the adopted size; model critical crossings in HY-8.'],
  sens:[{calc:'CUL', key:'D', vals:[0.9,1.05,1.2,1.35,1.5,1.8], out:[['HW','Headwater (m)']], xl:'Barrel diameter (m)', yl:'HW (m)', hl:(R)=>({y:R.CUL.I.HWa, label:'HW allowable'})}]},
 {id:'m18', no:18, name:'Detention / Retention', grp:'Hydrology & Drainage (MSMA)', tech:true, calcs:['DET','OSD','RET'],
  ov:'Detention pond sizing by critical storm duration, pond stage-storage, outlet and spillway; OSD for compounds; infiltration screening.',
  avail:['Pond location','Pre-development land use'], out:['JPS confirmation of detention criteria','Percolation tests'], rec:['Consider distributed detention (swales / multiple ponds) to reduce single pond footprint.'],
  sens:[{calc:'DET', key:'k', vals:[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2], out:[['Vreq','Required storage (m³)']], xl:'Allowable outflow factor k (Q_o = k·Q_pre)', yl:'Storage (m³)'}]},
 {id:'m19', no:19, name:'Flood Risk', grp:'Hydrology & Drainage (MSMA)', tech:true, calcs:['FPL'],
  ov:'Design flood level, freeboard and allowances to set minimum platform levels for flood-sensitive facilities.',
  avail:['JPS flood map / historical flood level'], out:['Official design flood level'], rec:['Flood study where the site is within a JPS flood-prone area.'],
  sens:[{calc:'FPL', key:'dfl', vals:[11.0,11.5,12.0,12.5,13.0,13.5,14.0], out:[['fillMax','Maximum raise (m)']], xl:'Design flood level (m RL)', yl:'Maximum platform raise (m)'}]},
 {id:'m20', no:20, name:'ESCP', grp:'Hydrology & Drainage (MSMA)', tech:true, calcs:['ESC'],
  ov:'Erosion and sediment control: sediment basins, silt traps, check dams, temporary drains and silt fence for construction staging.',
  avail:['Clearing & earthworks staging'], out:['Construction staging plan'], rec:['Stage clearing to limit disturbed area; maintain ESC BMPs after every storm.']},
 {id:'m21', no:21, name:'Road Design', grp:'Roads & Access', tech:true, calcs:['PAV'],
  ov:'Pavement concept for construction and permanent traffic: granular thickness by CBR method and traffic category for JKR flexible pavement.',
  avail:['Subgrade CBR','Traffic estimate'], out:['In-situ CBR along alignment'], rec:['Use geotextile separator and 350 mm sub-base on soft subgrade.'],
  sens:[{calc:'PAV', key:'cbr', vals:[2,3,4,5,6,8,10,15], out:[['treq','Required thickness (mm)']], xl:'Subgrade CBR (%)', yl:'Thickness (mm)'}]},
 {id:'m22', no:22, name:'Main Access', grp:'Roads & Access', tech:true, calcs:['ACC'],
  ov:'Main access geometry: gradient, swept path of design vehicle at the junction and sight distance.',
  avail:['Junction survey'], out:['JKR/PBT junction requirements'], rec:['Submit junction layout to JKR / PBT early.']},
 {id:'m23', no:23, name:'Internal Road', grp:'Roads & Access', tech:true, calcs:['RDQ'],
  ov:'Internal road network quantities (sub-grade, sub-base, base, surfacing, geotextile).',
  avail:['PV layout (road network)'], out:['Final road alignment'], rec:['Provide passing bays every 500 m on 4 m roads.']},
 {id:'m24', no:24, name:'Heavy Transport', grp:'Roads & Access', tech:true, calcs:['HVY'],
  ov:'Heaviest delivery check (main transformer): axle loads, crossings, gradients and clearances.',
  avail:['Transporter proposal'], out:['Route survey','Crossing structural ratings'], rec:['Commission route survey and culvert load rating.']},
 {id:'m25', no:25, name:'Crane Access', grp:'Roads & Access', tech:true, calcs:['CRN'],
  ov:'Crane hardstanding for transformer and heavy equipment lifts.',
  avail:['Lift plan'], out:['Crane selection & outrigger loads'], rec:['Working platform certificate before lifting (BRE 470 method).']},
 {id:'m26', no:26, name:'PV Foundation', grp:'Foundations & Structures', tech:true, calcs:['WND','PVP','PVS'],
  ov:'Wind actions on PV structures and PV pile design — compression, uplift, lateral and structural checks.',
  avail:['Tracker vendor loads','SI'], out:['Vendor pile load table and wind-tunnel report','Pull-out test results'], rec:['Pre-construction pile test programme in each geological zone before production piling.'],
  sens:[{calc:'PVP', key:'L', vals:[2.0,2.5,3.0,3.5,4.0,4.5,5.0], out:[['Qall','Compression (kN)'],['Tall','Uplift (kN)'],['Hall','Lateral (kN)']], xl:'Pile embedment L (m)', yl:'Allowable capacity (kN)', hl:(R)=>({y:R.PVP.I.Tw, label:'Uplift demand'})}]},
 {id:'m27', no:27, name:'Pile Foundation', grp:'Foundations & Structures', tech:true, calcs:['HEL','DRV','PTS'], custom:'pilecmp',
  ov:'Alternative pile systems (helical / screw, driven / spun), pile test schedule and pile option comparison.',
  avail:['SI','Pile vendor data'], out:['Vendor torque correlation','Manufacturer spun pile class table'], rec:['Do not select a pile system without test data in each zone.'],
  sens:[{calc:'DRV', key:'L', vals:[8,10,12,14,16,18], out:[['Qall','Allowable (kN)']], xl:'Pile length (m)', yl:'Allowable (kN)', hl:(R)=>({y:R.DRV.I.Pw, label:'Working load'})}]},
 {id:'m28', no:28, name:'Shallow Foundation', grp:'Foundations & Structures', tech:true, calcs:['BRG','SET','FDN_LGT'],
  ov:'Bearing capacity, settlement and general shallow foundations (lighting masts and miscellaneous equipment).',
  avail:['SI','Equipment loads'], out:['Plate load tests at platform'], rec:['Found pads on engineered platform fill compacted to 95% MDD, min 1.0 m depth.'],
  sens:[{calc:'BRG', key:'B', vals:[1.5,2,2.5,3,3.5,4,5], out:[['qa','Allowable bearing (kPa)']], xl:'Footing width B (m)', yl:'q_all (kPa)'}]},
 {id:'m29', no:29, name:'Inverter Foundation', grp:'Foundations & Structures', tech:true, calcs:['FDN_INV'],
  ov:'Inverter / MV skid pad foundation design.', avail:['Skid vendor data'], out:['Vendor skid load & anchor data'], rec:['Raise skids on plinths where local ground is below required RL.'],
  sens:[{calc:'FDN_INV', key:'B', vals:[2.4,2.8,3.2,3.6,4.0], out:[['qmax','Max bearing pressure (kPa)']], xl:'Footing width B (m)', yl:'q_max (kPa)', hl:(R)=>({y:R.FDN_INV.I.qa, label:'q_all'})}]},
 {id:'m30', no:30, name:'Transformer Foundation', grp:'Foundations & Structures', tech:true, calcs:['FDN_TX'],
  ov:'Main power transformer foundation and oil containment bund.', avail:['Transformer GA & weights'], out:['Oil volume & weight from vendor'], rec:['Include fire wall between transformers if separation insufficient (TNB).']},
 {id:'m31', no:31, name:'BESS Foundation', grp:'Foundations & Structures', types:['B'], tech:true, calcs:['BFDN'],
  ov:'BESS enclosure foundation: bearing, sliding, overturning, uplift and structural design.', avail:['BESS vendor data'], out:['Certified enclosure weight, COG and anchorage loads'], rec:['Strip / plinth foundations with cable entry pits per vendor GA.'],
  sens:[{calc:'BFDN', key:'B', vals:[2.8,3.2,3.6,4.0], out:[['qmax','Max bearing pressure (kPa)']], xl:'Footing width B (m)', yl:'q_max (kPa)', hl:(R)=>({y:R.BFDN.I.qa, label:'q_all'})}]},
 {id:'m32', no:32, name:'Substation Civil Works', grp:'Foundations & Structures', tech:true, calcs:['SUB'],
  ov:'Substation yard platform, surfacing, equipment foundations and fencing.', avail:['Substation layout'], out:['TNB substation civil requirements'], rec:['Coordinate earthing grid and cable trench levels with platform design.']},
 {id:'m33', no:33, name:'Structural Works', grp:'Foundations & Structures', tech:true, calcs:['LCB','RCF','STL'],
  ov:'Load combinations and structural element design (RC sections, steel members) for ancillary structures.', avail:['Architectural layouts'], out:['Building layouts'], rec:['Adopt MS EN Eurocodes with Malaysian NA; verify NA values.']},
 {id:'m34', no:34, name:'Cable Trench', grp:'Cable, Services & Ancillary', tech:true, calcs:['CTR'],
  ov:'Cable trench geometry checks and quantities for MV and LV/DC routes.', avail:['Cable schedule'], out:['Final cable schedule & route'], rec:['Standard trench sections per cable count.']},
 {id:'m35', no:35, name:'Underground Services', grp:'Cable, Services & Ancillary', tech:true, calcs:['UGS'],
  ov:'Ducted crossings under roads / drains and encasement.', avail:['Road & drain layout'], out:['Crossing schedule'], rec:['Provide 25% spare ducts at crossings.']},
 {id:'m36', no:36, name:'Retaining Walls', grp:'Cable, Services & Ancillary', tech:true, calcs:['RTW'],
  ov:'RC cantilever retaining walls at raised platform edges.', avail:['Platform levels'], out:['Wall alignment'], rec:['Use slopes in lieu of walls where space permits.'],
  sens:[{calc:'RTW', key:'B', vals:[1.8,2.0,2.2,2.4,2.6,2.8,3.0], out:[['FSs','Sliding FS'],['FSo','Overturning FS']], xl:'Base width B (m)', yl:'FS', hl:(R)=>({y:1.5, label:'FS 1.5'})}]},
 {id:'m37', no:37, name:'Fencing', grp:'Cable, Services & Ancillary', tech:true, calcs:['FEN'],
  ov:'Perimeter fence post and footing design under wind.', avail:['Fence specification'], out:['Client security specification'], rec:['Anti-climb fence with concrete footings at 3 m centres.'],
  sens:[{calc:'FEN', key:'L', vals:[0.5,0.6,0.7,0.8,0.9,1.0,1.2], out:[['FSl','Lateral FS']], xl:'Footing depth L (m)', yl:'FS', hl:(R)=>({y:R.FEN.I.FS, label:'FS required'})}]},
 {id:'m38', no:38, name:'Gates', grp:'Cable, Services & Ancillary', tech:true, calcs:['GAT'],
  ov:'Gate post foundations.', avail:['Gate specification'], out:[], rec:['Tie gate post footings with ground beam at main entrance.']},
 {id:'m39', no:39, name:'Security Infrastructure', grp:'Cable, Services & Ancillary', tech:true, calcs:['FDN_CCTV'],
  ov:'CCTV / lighting pole foundations and security infrastructure civil works.', avail:['Security layout'], out:['CCTV layout'], rec:['Coordinate pole locations with fence line and cable trench.']},
 {id:'m40', no:40, name:'Water Supply', grp:'Cable, Services & Ancillary', tech:true, calcs:['WSP'],
  ov:'Water demand, storage and supply pipe.', avail:['Water operator connection point'], out:['Water operator approval'], rec:['Provide rainwater harvesting for panel cleaning where practical.']},
 {id:'m41', no:41, name:'Sewerage', grp:'Cable, Services & Ancillary', tech:true, calcs:['SEW'],
  ov:'Population equivalent, sewage flow and septic / package plant screening.', avail:['Staffing plan'], out:['IWK / SPAN requirements'], rec:['Confirm treatment system type with SPAN/IWK.']},
 {id:'m42', no:42, name:'Fire-Water Civil Works', grp:'Cable, Services & Ancillary', tech:true, calcs:['FWC','FDN_FWT'],
  ov:'Civil / structural support for fire-water: tank foundation, pump house, hydrant main trench, appliance hardstanding and drainage. Specialist fire hydraulic design is separate.', avail:['Fire consultant demand'], out:['Fire-water demand & tank size (fire consultant / BOMBA)'], rec:['Separate C&S scope from fire hydraulic design in the tender.']},
 {id:'m43', no:43, name:'BESS Civil', grp:'BESS Civil', types:['B'], tech:true, calcs:['BPL'],
  ov:'BESS platform footprint, level, fill, drainage fall and containment requirement.', avail:['BESS layout'], out:['BOMBA separation requirements'], rec:['Freeze BESS layout only after BOMBA consultation.']},
 {id:'m44', no:44, name:'BESS Drainage', grp:'BESS Civil', types:['B'], tech:true, calcs:['BDR'],
  ov:'BESS platform drainage and diversion of potentially contaminated flows.', avail:['Platform grading'], out:['Isolation valve philosophy'], rec:['Provide isolation valve upstream of interceptor.']},
 {id:'m45', no:45, name:'BESS Containment', grp:'BESS Civil', types:['B'], tech:true, calcs:['BCON'],
  ov:'Containment volume for transformer oil, coolant, fire-water and rainfall.', avail:['Vendor oil / coolant volumes'], out:['Fire-water application rate & duration'], rec:['Size containment on confirmed fire-water demand; consider lined pond.']},
 {id:'m46', no:46, name:'Temporary Works', grp:'Construction', tech:true, calcs:['TMP'],
  ov:'Temporary facilities, laydown and temporary works screening.', avail:['Programme'], out:['Contractor temporary works design'], rec:['Temporary works register under BOWEC.']},
 {id:'m47', no:47, name:'Construction Logistics', grp:'Construction', tech:true, calcs:['LOG'],
  ov:'Delivery trips and piling productivity against programme.', avail:['Programme','Procurement plan'], out:['Contractor programme'], rec:['Traffic management plan for delivery peak.']},
 {id:'m48', no:48, name:'Quantity Take-Off', grp:'Commercial & Tender', kind:'qto', calcs:['QCON','QREB','QRD','QFDN']},
 {id:'m49', no:49, name:'BOQ', grp:'Commercial & Tender', kind:'boq'},
 {id:'m50', no:50, name:'Cost Estimate', grp:'Commercial & Tender', kind:'cost'},
 {id:'m51', no:51, name:'Tender Reconciliation', grp:'Commercial & Tender', kind:'recon'},
 {id:'m52', no:52, name:'Tender Technical Evaluation', grp:'Commercial & Tender', kind:'techeval'},
 {id:'m53', no:53, name:'Tender Clarifications', grp:'Commercial & Tender', kind:'clar'},
 {id:'m54', no:54, name:'Design Risk Register', grp:'Risk & Compliance', kind:'risk'},
 {id:'m55', no:55, name:'Constructability', grp:'Risk & Compliance', kind:'construct'},
 {id:'m56', no:56, name:'Value Engineering', grp:'Risk & Compliance', kind:'ve'},
 {id:'m57', no:57, name:'Authority Compliance', grp:'Risk & Compliance', kind:'authority'},
 {id:'m58', no:58, name:'Standards Register', grp:'Risk & Compliance', kind:'standards'},
 {id:'m59', no:59, name:'Assumption Register', grp:'Registers & Deliverables', kind:'assume'},
 {id:'m60', no:60, name:'Engineering Query Register', grp:'Registers & Deliverables', kind:'eq'},
 {id:'m61', no:61, name:'Drawing Register', grp:'Registers & Deliverables', kind:'drawings'},
 {id:'m62', no:62, name:'Report Register', grp:'Registers & Deliverables', kind:'reports'},
 {id:'m63', no:63, name:'Deliverables', grp:'Registers & Deliverables', kind:'deliv'},
 {id:'m64', no:64, name:'Final Tender Review', grp:'Report', kind:'review'},
 {id:'m65', no:65, name:'Report Generator', grp:'Report', kind:'report'},
];
MODULES.forEach(m => { m.types = m.types || ['A','B']; });
const MOD = {}; MODULES.forEach(m => MOD[m.id] = m);
const modApplies = m => m.types.includes(P.type);
function modOfCalc(cid){ return MODULES.find(m => (m.calcs || []).includes(cid)); }

/* Required calculator index (brief §94) → calc IDs */
const REQ_CALCS = [
 [1,'Cut & Fill','CF'],[2,'Earthwork Balance','EWB'],[3,'Slope Statistics','TOPO'],[4,'Bearing Capacity','BRG'],[5,'Settlement Screening','SET'],[6,'PV Pile Compression','PVP'],[7,'PV Pile Uplift','PVP'],[8,'PV Pile Lateral','PVP'],
 [9,'Helical / Screw Pile','HEL'],[10,'Driven Pile','DRV'],[11,'Structural Pile Check','PVS'],[12,'Pile Test Schedule','PTS'],[13,'Shallow Foundation Bearing','FDN_INV'],[14,'Sliding','FDN_INV'],[15,'Overturning','FDN_LGT'],[16,'Uplift','FDN_INV'],
 [17,'Punching Shear','FDN_TX'],[18,'RC Flexure','RCF'],[19,'Steel Member Check','STL'],[20,'Wind Load','WND'],[21,'Catchment Analysis','CAT'],[22,'Rational Method','RAT'],[23,'Time of Concentration','TC'],[24,'Rainfall / IDF','IDF'],
 [25,'Manning Drain','MAN'],[26,'Drain Sizing','DSZ'],[27,'Culvert','CUL'],[28,'Detention Pond','DET'],[29,'OSD','OSD'],[30,'Retention / Infiltration','RET'],[31,'Flood Platform Level','FPL'],[32,'Scour Protection','SCR'],
 [33,'ESCP sizing','ESC'],[34,'Slope Stability Screening','SLP'],[35,'Road Pavement','PAV'],[36,'Heavy Transport','HVY'],[37,'Cable Trench Quantity','CTR'],[38,'Retaining Wall','RTW'],[39,'Fence Foundation','FEN'],[40,'BESS Foundation','BFDN'],
 [41,'BESS Platform','BPL'],[42,'BESS Containment','BCON'],[43,'Concrete Quantity','QCON'],[44,'Reinforcement Quantity','QREB'],[45,'Road Quantity','RDQ'],[46,'Drainage Quantity','QDRN'],[47,'Foundation Quantity','QFDN'],[48,'BOQ','@m49'],[49,'Cost Sensitivity','@m50'],[50,'Tender Variance','@m51'],
];

/* report chapter mapping: report section number → module(s) */
const REPORT_TECH = [
 [22,'Topographical Assessment',['m8','m12']],[23,'Geotechnical Assessment',['m10']],[24,'Earthworks',['m11','m13']],[25,'Grading',['m12']],[26,'Slope Engineering',['m14']],
 [27,'Hydrology',['m15']],[28,'Drainage',['m16']],[29,'Culvert Design',['m17']],[30,'Detention',['m18']],[31,'Flood Risk',['m19']],[32,'ESCP',['m20']],
 [33,'Road Design',['m21','m22','m23']],[34,'Heavy Transport',['m24','m25']],[35,'PV Foundation',['m26']],[36,'Pile Calculations',['m27']],[37,'Equipment Foundations',['m28','m29','m30']],
 [38,'Structural Works',['m33','m32']],[39,'Cable Trench',['m34','m35']],[40,'Retaining Walls',['m36']],[41,'Ancillary Civil Works',['m37','m38','m39','m40','m41','m42','m46','m47']],
 [42,'BESS Civil',['m43'],'B'],[43,'BESS Foundation',['m31'],'B'],[44,'BESS Drainage',['m44'],'B'],[45,'BESS Containment',['m45'],'B'],
];
