'use strict';
/* ==========================================================================
   PAGES — custom input panels for technical modules and all non-calculation
   module pages (dashboard, registers, commercial, compliance, report)
   ========================================================================== */
const CUSTOM = {
  site(){
    let tot = 0, n = 0; SITE_ITEMS.forEach(s => { const r = (P.site[s[0]] || {}).rating; if (RATING_W[r]){ tot += RATING_W[r]; n++; } });
    const avg = n ? tot / n : 0, lvl = avg >= 2.4 ? 'HIGH' : avg >= 1.6 ? 'MODERATE' : 'LOW';
    let h = `<div class="card"><h3>Site constraint matrix <span class="badge ${lvl === 'HIGH' ? 'fail' : lvl === 'MODERATE' ? 'warn' : 'pass'}">Overall ${lvl} (${fmt(avg, 2)})</span></h3><div class="tw"><table class="t"><thead><tr><th>Category</th><th>Constraint</th><th>Rating</th><th>Notes / evidence</th><th>Linked calculation evidence</th></tr></thead><tbody>`;
    const ev = {S2: () => R.TOPO ? `Max slope ${f1(R.TOPO.res.smax)}°, ${f1(R.TOPO.res.steepPct)}% > 10°` : '', S3: () => R.FPL ? `Max platform raise ${f2(R.FPL.res.fillMax)} m` : '', S5: () => R.GEO ? `${R.GEO.res.softTop} BH with soft clay` : '', S6: () => R.GEO && R.GEO.res.hardDepth != null ? `Hard stratum ${f1(R.GEO.res.hardDepth)} m bgl` : '', S7: () => R.GEO ? `${R.GEO.res.corrosive} BH aggressive` : ''};
    SITE_ITEMS.forEach(s => { const v = P.site[s[0]] || {}; h += `<tr><td>${esc(s[1])}</td><td>${esc(s[2])}</td><td><select data-bind="site.${s[0]}.rating"${dis('edit')}>${['','Low','Moderate','High'].map(o => `<option${o === v.rating ? ' selected' : ''}>${o}</option>`).join('')}</select></td><td><input data-bind="site.${s[0]}.note" value="${esc(v.note || '')}"${dis('edit')}></td><td class="small muted">${esc(ev[s[0]] ? ev[s[0]]() : '')}</td></tr>`; });
    return h + '</tbody></table></div><p class="small muted">Weighted rating: Low = 1, Moderate = 2, High = 3. Ratings feed the Site Constraints chapter of the report.</p></div>';
  },
  topo(){
    const D = getDEM();
    return `<div class="card"><h3>DTM grid ${D.src === 'demo' ? '<span class="badge warn">synthetic demonstration grid</span>' : '<span class="badge pass">user DTM</span>'}</h3><div class="grid2"><div>${figDEM()}</div><div>${figSlopeBands()}
      <p class="small">Paste a gridded DTM (rows north → south, comma / space separated RL values) to replace the demonstration grid. Platforms (section C of Cut &amp; Fill) are defined in grid cells.</p>
      <div class="row"><label class="small">Cell size (m)</label><input id="demdx" class="num" style="width:80px" value="${D.dx}"></div>
      <textarea id="demtxt" rows="4" placeholder="12.1, 12.3, 12.6 …&#10;12.0, 12.2, 12.4 …"${dis('edit')}></textarea>
      <div class="row" style="margin-top:6px"><button class="sm" data-act="demimport"${dis('edit')}>Import DTM grid</button><button class="sm" data-act="demreset"${dis('edit')}>Restore demonstration grid</button></div></div></div></div>`;
  },
  lots(){ return `<div class="card"><h3>Lot schedule</h3>${editTable('tables.lots', [{k:'lot', l:'Lot'}, {k:'title', l:'Title'}, {k:'area', l:'Area (ha)', n:1}, {k:'status', l:'Status', t:'sel', o:['Verified','Pending','Disputed']}], {tpl:{lot:'', title:'', area:0, status:'Pending'}, perm:'edit'})}</div>`; },
  bh(){
    const bhs = P.tables.bh || [];
    let h = `<div class="card"><h3>Boreholes (measured data)</h3>${editTable('tables.bh', [{k:'id', l:'ID'}, {k:'lat', l:'Lat', n:1}, {k:'lon', l:'Lon', n:1}, {k:'rl', l:'RL (m)', n:1}, {k:'depth', l:'Depth (m)', n:1}, {k:'gwl', l:'GWL (m bgl)', n:1}, {k:'cbr', l:'CBR %', n:1}, {k:'res', l:'Resist. Ω·cm', n:1}, {k:'ph', l:'pH', n:1}, {k:'so4', l:'SO₄ mg/kg', n:1}, {k:'cl', l:'Cl mg/kg', n:1}], {perm:'edit', tpl:{id:'BH-NEW', lat:0, lon:0, rl:0, depth:10, gwl:2, cbr:5, res:3000, ph:6, so4:100, cl:50, layers:[[0,3,'CLAY','CLAY',5],[3,10,'SAND','SAND',20]]}})}</div>`;
    h += `<div class="card"><h3>Layers (from / to m bgl, description, type, SPT N)</h3><div class="grid2">${bhs.map((b, i) => `<div><b>${esc(b.id)}</b>${editTable(`tables.bh.${i}.layers`, [{k:'0', l:'From', n:1}, {k:'1', l:'To', n:1}, {k:'2', l:'Description', w:140}, {k:'3', l:'Type', t:'sel', o:['CLAY','SILT','SAND','ROCK']}, {k:'4', l:'SPT N', n:1}], {perm:'edit', tpl:[0,1,'','CLAY',5]})}</div>`).join('')}</div></div>`;
    return h + `<div class="card"><h3>Graphical soil profile</h3>${figSoil()}</div>`;
  },
  grading(){ return `<div class="card"><h3>Grading zone map</h3><div class="grid2"><div>${figGrading()}</div><div class="small"><p>Zones are computed per DTM cell from the N–S and E–W slopes against the mounting-system tolerance. Platform cells are excluded.</p><p><b>No grading</b> — within tolerance; <b>Moderate</b> — ≤ 1.5 × tolerance; <b>Major</b> — > 1.5 × tolerance.</p></div></div></div>`; },
  platforms(){ return `<div class="card"><h3>Platforms (grid cells; x → east, y → south from NW corner)</h3>${editTable('tables.platforms', [{k:'id', l:'ID'}, {k:'name', l:'Name', w:180}, {k:'x0', l:'x₀', n:1}, {k:'y0', l:'y₀', n:1}, {k:'w', l:'w (cells)', n:1}, {k:'h', l:'h (cells)', n:1}, {k:'auto', l:'Auto RL', t:'sel', o:[true, false]}, {k:'rl', l:'User RL', n:1}, {k:'gx', l:'Cross-fall %', n:1}], {perm:'edit', tpl:{id:'PF-NEW', name:'New platform', x0:5, y0:5, w:2, h:2, rl:0, gx:0.5, gy:0, auto:true}})}<div style="margin-top:8px">${figDEM()}</div></div>`; },
  hydro(){ return `<div class="card"><h3>Sub-catchments (pre / post development)</h3>${editTable('tables.sc', [{k:'id', l:'ID'}, {k:'area', l:'A (ha)', n:1}, {k:'preUse', l:'Pre land use', w:120}, {k:'cPre', l:'C pre', n:1}, {k:'postUse', l:'Post land use', w:140}, {k:'cPost', l:'C post', n:1}, {k:'L', l:'L overland (m)', n:1}, {k:'S', l:'S (%)', n:1}, {k:'nPre', l:'n* pre', n:1}, {k:'nPost', l:'n* post', n:1}, {k:'Lc', l:'L drain (m)', n:1}, {k:'Sc', l:'S drain (%)', n:1}], {perm:'edit', tpl:{id:'SC-N', area:5, preUse:'Scrub', cPre:0.4, postUse:'PV array', cPost:0.5, L:80, S:2, nPre:0.06, nPost:0.045, Lc:300, Sc:0.5}})}
      <div class="grid2" style="margin-top:8px"><div>${figIDF()}</div><div>${figCatch()}</div></div></div>`; },
  pilecmp(){
    const W = P.options.weights, S = P.options.scores, wsum = sum(Object.values(W).map(Number));
    const cap = {'Driven steel': R.PVP ? `${f1(R.PVP.res.Tall)} kN uplift` : '', 'Screw pile': R.HEL ? `${f1(R.HEL.res.Tall)} kN uplift` : '', 'Helical pile': R.HEL ? `${f1(R.HEL.res.Tall)} kN uplift` : '', 'Spun pile': R.DRV ? `${f0(R.DRV.res.Qall)} kN comp.` : ''};
    let h = `<div class="card"><h3>Pile option comparison (score 1–5; 5 = most favourable)</h3><div class="tw"><table class="t"><thead><tr><th>Criterion</th><th class="c">Weight</th>${PILE_OPTS.map(o => `<th class="c">${esc(o)}</th>`).join('')}</tr></thead><tbody>`;
    h += `<tr class="hd"><td>Calculated capacity (evidence)</td><td></td>${PILE_OPTS.map(o => `<td class="c small">${esc(cap[o] || 'not calculated')}</td>`).join('')}</tr>`;
    PILE_CRIT.forEach(([k, l]) => { h += `<tr><td>${esc(l)}</td><td><input class="num" data-num="1" data-bind="options.weights.${k}" value="${W[k]}" style="width:56px"${dis('edit')}></td>${PILE_OPTS.map(o => `<td><input class="num" data-num="1" data-bind="options.scores.${o}.${k}" value="${S[o][k]}" style="width:48px"${dis('edit')}></td>`).join('')}</tr>`; });
    if (wsum > 0){ const tot = PILE_OPTS.map(o => sum(PILE_CRIT.map(([k]) => (+W[k] || 0) * (+S[o][k] || 0))) / wsum); const best = Math.max(...tot);
      h += `<tr class="tot"><td>Weighted score</td><td class="c">${wsum}</td>${tot.map(t => `<td class="c">${fmt(t, 2)}${t === best ? ' ★' : ''}</td>`).join('')}</tr>`; }
    h += '</tbody></table></div>';
    h += wsum > 0 ? `<p class="small">Ranking based on <b>user-defined decision criteria</b> (weights). ★ = highest weighted score. Engineering basis: calculated capacities above and pile tests; final selection requires Engineer confirmation.</p>` : `<p class="small"><b>No option is declared preferred</b> — decision criteria (weights) have not been defined. Enter weights to compute a weighted ranking.</p>`;
    return h + '</div>';
  },
};

/* ---------- non-technical pages ---------- */
function pageHead(m, sub){ return `<div class="ph"><h1><span class="mno">${m.no}.</span>${esc(m.name)}</h1><span class="sub">${esc(sub || m.grp)}</span></div>`; }
const PAGES = {
  dash(m){
    const ids = Object.keys(R), pass = ids.filter(i => R[i].status === 'pass').length, fail = ids.filter(i => R[i].status === 'fail').length;
    const cs = costSummary(), mi = missingInfo(), hi = RISKS.filter(r => r.level === 'High').length;
    let h = pageHead(m, P.type === 'B' ? 'Type B — Solar Farm + BESS' : 'Type A — Solar Farm');
    if (P.sample) h += `<div class="demo" style="margin-bottom:10px">${DEMO_FLAG}</div>`;
    h += `<div class="grid4">${[[`${fmt(+P.info.mwac, 0)} MWac`, `${fmt(+P.info.mwp, 0)} MWp PV${P.type === 'B' ? ` · ${fmt(+P.info.bessMW, 0)} MW / ${fmt(+P.info.bessMWh, 0)} MWh BESS` : ''}`], [`${pass} / ${ids.length}`, 'Calculations compliant'], [fail, 'Calculations with non-compliance'], [`RM ${fmt(cs.total / 1e6, 2)} m`, 'C&S engineering estimate'], [hi, 'High design risks'], [TENDER.gaps.length, 'Tender scope gaps'], [TENDER.issues.length, 'Tender line issues'], [Object.values(mi.tags).reduce((a, b) => a + b.length, 0) + mi.docs.length, 'Outstanding information items']].map(([v, l]) => `<div class="kpi"><div class="v">${esc(v)}</div><div class="l">${esc(l)}</div></div>`).join('')}</div>`;
    const flow = [['Project info','m2'],['Location','m3'],['Documents','m5'],['Missing info','m5'],['Design basis','m15'],['Standards','m58'],['Inputs','m10'],['Calculation','m26'],['Checks','m64'],['Design','m16'],['Quantity','m48'],['Cost','m50'],['Reconciliation','m51'],['Risk','m54'],['Compliance','m57'],['Recommendation','m64'],['A4 report','m65']];
    h += `<div class="card" style="margin-top:12px"><h3>Workflow</h3><div class="row" style="gap:4px">${flow.map(([t, id], i) => `<a class="badge ${i < 3 ? 'pass' : 'a'}" href="#${id}" style="text-decoration:none">${esc(t)}</a>${i < flow.length - 1 ? '<span class="muted">→</span>' : ''}`).join('')}</div></div>`;
    h += `<div class="grid2"><div class="card"><h3>Module status</h3><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:4px">${MODULES.filter(modApplies).map(x => { const st = moduleStatus(x); return `<a href="#${x.id}" style="text-decoration:none;border:1px solid var(--bd);border-left:4px solid ${st === 'fail' ? 'var(--ng)' : st === 'pass' ? 'var(--ok)' : st === 'warn' ? '#D4A24A' : 'var(--bd2)'};padding:3px 6px;border-radius:3px;font-size:11.5px;color:var(--tx);background:#fff">${x.no}. ${esc(x.name)}</a>`; }).join('')}</div></div>
      <div class="card"><h3>Engineering non-compliances (auto-generated from calculations)</h3>${ids.filter(i => R[i].status === 'fail').flatMap(i => R[i].checks.filter(k => !k.pass).map(k => `<div class="chk fail"><div class="cl"><a href="#${(modOfCalc(i) || {}).id}">${esc(CALCS[i].no)} ${esc(CALCS[i].title)}</a></div><div class="cm">${esc(k.msg)}</div></div>`)).join('') || '<p class="muted">None.</p>'}</div></div>`;
    h += `<div class="grid2"><div class="card"><h3>Top risks</h3>${riskTable(RISKS.slice(0, 5))}</div><div class="card"><h3>Cost by bill (RM)</h3>${barChart({labels: Object.keys(cs.bills).map(b => b.replace(/^\d+ /, '')), values: Object.values(cs.bills).map(v => v / 1e6), unit: 'm', lw: 180, dp: 2})}</div></div>`;
    h += `<div class="card"><h3>Required calculators (brief §94)</h3><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:3px">${REQ_CALCS.map(([n, t, id]) => { const mod = id.startsWith('@') ? MOD[id.slice(1)] : modOfCalc(id); const ap = id.startsWith('@') || calcApplies(id); const st = id.startsWith('@') ? 'info' : ap ? R[id].status : 'na'; return `<a href="#${mod ? mod.id : 'm1'}" ${!id.startsWith('@') && ap ? `data-scroll="calc-${id}"` : ''} style="text-decoration:none;font-size:11.5px;color:${ap ? 'var(--tx)' : 'var(--tx2)'}">${n}. ${esc(t)} ${ap ? badge(st, st === 'info' ? 'OK' : undefined) : '<span class="badge na">Type B only</span>'}</a>`; }).join('')}</div></div>`;
    return h;
  },
  info(m){
    const F = [['name','Project name'],['number','Project number'],['client','Client'],['developer','Developer'],['epc','EPC'],['consultant','C&S consultant'],['location','Location'],['state','State'],['district','District'],['mukim','Mukim'],['pbt','PBT (blank = auto from database)'],['lot','Lot'],['landArea','Land area (ha)',1],['mwp','PV MWp',1],['mwac','PV MWac',1],['bessMW','BESS MW',1],['bessMWh','BESS MWh',1],['gridV','Grid voltage'],['substation','Substation'],['poi','POI'],['stage','Project stage'],['cod','COD'],['prepared','Prepared by'],['checked','Checked by'],['approved','Approved by (PE / PEPC)']];
    let h = pageHead(m);
    h += `<div class="card"><h3>Project type — controls tabs, calculations, BOQ, risks, reports, standards and authority requirements</h3><div class="row"><select data-act="settype"${dis('admin') && dis('approve') ? ' disabled' : ''} style="max-width:360px"><option value="A"${P.type === 'A' ? ' selected' : ''}>TYPE A — Solar Farm</option><option value="B"${P.type === 'B' ? ' selected' : ''}>TYPE B — Solar Farm + BESS</option></select><span class="small muted">Changing the type re-configures the workflow; BESS-specific modules, calculations and BOQ items are excluded from Type A.</span></div></div>`;
    h += `<div class="card"><div class="grid3">${F.map(([k, l, n]) => { const bess = /bess/.test(k); if (bess && P.type === 'A') return `<div><label class="small muted">${esc(l)}</label><input value="N/A — Type A" disabled></div>`; return `<div><label class="small muted">${esc(l)}</label><input ${n ? 'class="num" data-num="1"' : ''} data-bind="info.${k}" value="${esc(P.info[k] == null ? '' : P.info[k])}"${dis('edit')}></div>`; }).join('')}</div>
      <p class="small muted">PBT identified: <b>${esc(pbtName())}</b> (${P.info.pbt ? 'user-entered' : 'from PBT database — AUTHORITY CONFIRMATION REQUIRED'}).</p></div>`;
    return h;
  },
  coords(m){
    let h = pageHead(m) + `<div class="card"><p class="small">Enter WGS84 decimal degrees; DMS and UTM (WGS84, EPSG:326xx) are computed. GDM2000 Peninsular RSO (EPSG:3375) / Cassini coordinates shall be entered from the licensed surveyor — not converted by the platform.</p>`;
    h += editTable('coords', [{k:'label', l:'Feature', w:160}, {k:'lat', l:'Lat (DD)', n:1}, {k:'lon', l:'Lon (DD)', n:1}, {k:'_dms', l:'DMS', ro:true, fmt:(v, r) => isNum(+r.lat) && r.lat !== '' ? `${toDMS(+r.lat,'N','S')}<br>${toDMS(+r.lon,'E','W')}` : ''}, {k:'_utm', l:'UTM E / N', ro:true, n:1, fmt:(v, r) => { if (r.lat === '' || !isNum(+r.lat)) return ''; const u = toUTM(+r.lat, +r.lon); return `${fmt(u.E, 1)}<br>${fmt(u.N, 1)} <span class="muted">${u.zone}N</span>`; }}, {k:'rsoE', l:'RSO E (surveyor)', n:1}, {k:'rsoN', l:'RSO N (surveyor)', n:1}, {k:'datum', l:'Datum', t:'sel', o:['WGS84','GDM2000','Kertau 1948']}, {k:'crs', l:'CRS'}, {k:'epsg', l:'EPSG'}, {k:'src', l:'Source', w:140}], {perm:'edit', tpl:{id:'', label:'New point', lat:'', lon:'', src:'', datum:'WGS84', crs:'Geographic', epsg:'4326', rsoE:'', rsoN:''}});
    return h + `</div><div class="card"><h3>Key plan</h3>${figLayout()}</div>`;
  },
  location(m){
    const cen = (P.coords || []).find(c => /centroid/i.test(c.label)) || (P.coords || [])[0];
    let h = pageHead(m) + `<div class="grid2"><div class="card"><h3>Location</h3><table class="t"><tbody>${[['Location', P.info.location], ['Mukim', P.info.mukim], ['District', P.info.district], ['State', P.info.state], ['PBT', pbtName()], ['Lot', P.info.lot], ['Land area', fmt(+P.info.landArea, 1) + ' ha'], ['Centroid', cen ? `${(+cen.lat).toFixed(5)}, ${(+cen.lon).toFixed(5)}` : '—']].map(([k, v]) => `<tr><th style="width:35%">${esc(k)}</th><td>${esc(v)}</td></tr>`).join('')}</tbody></table>
      ${cen ? `<p><a href="https://www.google.com/maps?q=${cen.lat},${cen.lon}" target="_blank" rel="noopener">Open centroid in Google Maps ↗</a></p>` : ''}
      <h3 style="margin-top:12px">Authority jurisdiction (screening)</h3><ul class="tight"><li>Local authority: <b>${esc(pbtName())}</b></li><li>JPS Negeri ${esc(P.info.state)} — drainage, flood, river reserve</li><li>JKR / PBT — access to public road</li><li>DOE Negeri ${esc(P.info.state)} — EIA screening, LD-P2M2</li><li>BOMBA Negeri ${esc(P.info.state)}${P.type === 'B' ? ' — incl. BESS fire safety' : ''}</li><li>${P.info.state === 'Sabah' ? 'SESB' : P.info.state === 'Sarawak' ? 'Sarawak Energy' : 'TNB'} — grid interface</li></ul><p class="small wbox"><b>AUTHORITY CONFIRMATION REQUIRED</b> — jurisdiction from database screening.</p></div>
      <div class="card"><h3>Key plan (schematic)</h3>${figLayout()}</div></div>`;
    return h;
  },
  docs(m){
    const mi = missingInfo();
    let h = pageHead(m) + `<div class="card"><h3>Document register</h3>${editTable('docs', [{k:'id', l:'Ref'}, {k:'title', l:'Title', w:240}, {k:'cat', l:'Category', w:110}, {k:'from', l:'From'}, {k:'status', l:'Status', t:'sel', o:['Received','Partial','Pending','Not available']}, {k:'rev', l:'Rev'}, {k:'date', l:'Date'}, {k:'mod', l:'Module', t:'sel', o:MODULES.map(x => x.id)}, {k:'notes', l:'Notes'}], {tpl:{id:'DOC-', title:'', cat:'', from:'', status:'Pending', rev:'0', date:'', mod:'m5', notes:''}})}</div>`;
    h += `<div class="card"><h3>Missing information (derived from calculations and document status)</h3><table class="t"><thead><tr><th>Category</th><th>Item</th><th>Source</th></tr></thead><tbody>${Object.entries(mi.tags).flatMap(([t, ws]) => ws.map(w => `<tr><td><span class="badge warn">${esc(WARN[t])}</span></td><td>${esc(w.text)}</td><td class="muted">${esc(CALCS[w.calc].no)}</td></tr>`)).join('')}${mi.docs.map(d => `<tr><td><span class="badge fail">DOCUMENT ${esc(d.status.toUpperCase())}</span></td><td>${esc(d.title)}</td><td class="muted">${esc(d.id)}</td></tr>`).join('')}</tbody></table></div>`;
    return h;
  },
  checklist(m){
    let done = 0, tot = 0;
    const rows = CHECK_ROWS.filter(r => !r[5] || r[5] === P.type).map(r => { const [id, cat, item, mod, auto] = r; let a = '—';
      if (auto.startsWith('calc:')){ const c = auto.slice(5); a = R[c] ? (R[c].status === 'fail' ? 'Non-compliant' : 'Calculated') : 'N/A'; }
      else if (auto.startsWith('doc:')){ const d = (P.docs || []).find(x => x.cat === auto.slice(4)); a = d ? d.status : 'Not registered'; }
      const man = (P.checklist[id] || {}).status || ''; const st = man || (a === 'Calculated' || a === 'Received' ? 'Yes' : a === 'Non-compliant' || a === 'Partial' ? 'Partial' : 'No');
      tot++; if (st === 'Yes' || st === 'N/A') done++; return {id, cat, item, mod, a, man, st}; });
    let h = pageHead(m) + `<div class="card"><h3>C&amp;S tender checklist <span class="badge ${done / tot > 0.8 ? 'pass' : 'warn'}">${done}/${tot} complete (${f0(done / tot * 100)}%)</span></h3><p class="small muted">Status is automatic from calculation results and document register unless overridden. The checklist is linked to — not a substitute for — the engineering calculations.</p><div class="tw"><table class="t"><thead><tr><th>ID</th><th>Category</th><th>Item</th><th>Automatic evidence</th><th>Override</th><th>Status</th><th>Remarks</th></tr></thead><tbody>`;
    let lastCat = '';
    rows.forEach(r => { if (r.cat !== lastCat){ h += `<tr class="hd"><td colspan="7">${esc(r.cat)}</td></tr>`; lastCat = r.cat; }
      h += `<tr><td>${r.id}</td><td class="small">${esc(r.cat)}</td><td><a href="#${r.mod}">${esc(r.item)}</a></td><td class="small">${esc(r.a)}</td><td><select data-bind="checklist.${r.id}.status"${dis('registers')}>${['','Yes','Partial','No','N/A'].map(o => `<option${o === r.man ? ' selected' : ''}>${o}</option>`).join('')}</select></td><td>${badge(r.st === 'Yes' ? 'pass' : r.st === 'Partial' ? 'warn' : r.st === 'N/A' ? 'na' : 'fail', r.st)}</td><td><input data-bind="checklist.${r.id}.note" value="${esc((P.checklist[r.id] || {}).note || '')}"${dis('registers')}></td></tr>`; });
    return h + '</tbody></table></div></div>';
  },
  qto(m){
    let h = pageHead(m) + `<p class="small">Quantities are generated automatically from calculation results — every quantity is traceable to the originating calculation. Summary calculators (concrete, reinforcement, road, drainage, foundation) are shown below.</p>`;
    h += `<div class="card"><h3>Quantity take-off by BOQ item</h3><div class="tw"><table class="t"><thead><tr><th>Item</th><th>Description</th><th>Unit</th><th class="n">Total qty</th><th>Contributions (calculation → qty → basis)</th></tr></thead><tbody>${boqRows().map(r => { const it = QTO.items[r.key]; return `<tr><td>${esc(r.key)}</td><td>${esc(r.desc)}</td><td>${esc(r.unit)}</td><td class="n"><b>${fmt(r.qty, r.qty < 100 ? 2 : 0)}</b></td><td class="small">${it.src.map(s => `${s.calc ? `<a href="#${(modOfCalc(s.calc) || {}).id}" data-scroll="calc-${s.calc}">${esc(CALCS[s.calc].no)}</a>` : 'Fixed'} → ${fmt(s.qty, s.qty < 100 ? 2 : 0)}${s.basis ? ' (' + esc(s.basis) + ')' : ''}`).join('<br>')}</td></tr>`; }).join('')}</tbody></table></div></div>`;
    return h + m.calcs.filter(calcApplies).map(calcBlock).join('');
  },
  boq(m){
    const rows = boqRows(), cs = costSummary(rows); let lastBill = '';
    let h = pageHead(m) + `<div class="row noprint" style="margin-bottom:8px"><button class="sm" data-act="csvboq">Export BOQ (CSV)</button><span class="small muted">Amount = Qty × Rate. Rates editable by QS / Tender Engineer / PE. Demonstration rates.</span></div>`;
    h += `<div class="card"><div class="tw"><table class="t"><thead><tr><th>Item</th><th>Description</th><th>Unit</th><th class="n">Quantity</th><th class="n">Rate (RM)</th><th class="n">Amount (RM)</th><th>Calculation ref.</th><th>Drawing ref.</th><th>Assumption</th><th>Confidence</th><th>Remarks</th></tr></thead><tbody>`;
    rows.forEach(r => { if (r.bill !== lastBill){ if (lastBill) h += `<tr class="tot"><td colspan="5">Subtotal — ${esc(lastBill)}</td><td class="n">${fmt(cs.bills[lastBill], 0)}</td><td colspan="5"></td></tr>`; h += `<tr class="hd"><td colspan="11">BILL ${esc(r.bill)}</td></tr>`; lastBill = r.bill; }
      h += `<tr><td>${esc(r.key)}</td><td>${esc(r.desc)}</td><td>${esc(r.unit)}</td><td class="n">${fmt(r.qty, r.qty < 100 ? 2 : 0)}</td><td class="n"><input class="num" style="width:80px" data-rate="${r.key}" value="${baseRate(r.key)}"${dis('rates')}></td><td class="n">${fmt(r.amount, 0)}</td><td class="small">${esc(r.calcs)}</td><td class="small">${esc(r.dwg)}</td><td class="small" style="max-width:220px">${esc(r.basis)}</td><td>${badge(r.conf === 'High' ? 'pass' : r.conf === 'Medium' ? 'warn' : 'fail', r.conf)}</td><td><input data-bind="boqRemarks.${r.key}" value="${esc(r.remarks)}"${dis('rates')}></td></tr>`; });
    if (lastBill) h += `<tr class="tot"><td colspan="5">Subtotal — ${esc(lastBill)}</td><td class="n">${fmt(cs.bills[lastBill], 0)}</td><td colspan="5"></td></tr>`;
    h += `<tr class="tot"><td colspan="5">TOTAL DIRECT COST</td><td class="n">${fmt(cs.direct, 0)}</td><td colspan="5"></td></tr></tbody></table></div></div>`;
    return h;
  },
  cost(m){
    const cs = costSummary(), tor = sensitivityTornado(20), cc = P.costCfg;
    let h = pageHead(m);
    h += `<div class="grid2"><div class="card"><h3>Cost estimate summary</h3><table class="t"><tbody>${Object.entries(cs.bills).map(([b, v]) => `<tr><td>${esc(b)}</td><td class="n">${fmt(v, 0)}</td></tr>`).join('')}<tr class="tot"><td>Direct cost</td><td class="n">${fmt(cs.direct, 0)}</td></tr>
      <tr><td>Preliminaries <input class="num" data-num="1" data-bind="costCfg.prelimPct" value="${cc.prelimPct}" style="width:54px"${dis('rates')}> %</td><td class="n">${fmt(cs.prelim, 0)}</td></tr><tr><td>Design <input class="num" data-num="1" data-bind="costCfg.designPct" value="${cc.designPct}" style="width:54px"${dis('rates')}> %</td><td class="n">${fmt(cs.design, 0)}</td></tr><tr><td>Contingency <input class="num" data-num="1" data-bind="costCfg.contPct" value="${cc.contPct}" style="width:54px"${dis('rates')}> %</td><td class="n">${fmt(cs.cont, 0)}</td></tr>
      <tr class="tot"><td>TOTAL C&amp;S ESTIMATE (RM)</td><td class="n">${fmt(cs.total, 0)}</td></tr><tr><td class="muted">Per MWac</td><td class="n muted">${fmt(cs.total / Math.max(+P.info.mwac, 1), 0)}</td></tr></tbody></table></div>
      <div class="card"><h3>Cost sensitivity — rate adjustments</h3><table class="t"><thead><tr><th>Rate group</th><th class="n">Adjustment (%)</th></tr></thead><tbody>${Object.entries(SENS_GROUPS).map(([g, l]) => `<tr><td>${esc(l)}</td><td class="n"><input class="num" data-num="1" data-bind="rateMult.${g}" value="${(P.rateMult || {})[g] || 0}" style="width:70px"${dis('rates')}></td></tr>`).join('')}</tbody></table>
      <p class="small">Resulting total: <b>RM ${fmt(cs.total, 0)}</b>. Adjustments apply to all BOQ items in the group.</p></div></div>`;
    h += `<div class="grid2"><div class="card"><h3>Tornado — ±20% rate change</h3>${barChart({labels: tor.out.flatMap(o => [o.label + ' +20%', o.label + ' −20%']), values: tor.out.flatMap(o => [o.hi / 1e3, o.lo / 1e3]), unit: 'k RM', lw: 200, colors: tor.out.flatMap(() => ['#B0413E', '#3E7D4F']), dp: 0})}</div>
      <div class="card"><h3>Cost vs design option (value engineering)</h3>${barChart({labels: P.ve.flatMap(v => [v.id + ' base', v.id + ' alternative']), values: P.ve.flatMap(v => [veCost(VE_DEFAULT.find(d => d.id === v.id) || v, 'base') / 1e3, veCost(VE_DEFAULT.find(d => d.id === v.id) || v, 'alt') / 1e3]), unit: 'k RM', lw: 140, colors: P.ve.flatMap(() => ['#9E6035', '#D99058']), dp: 0})}</div></div>`;
    return h;
  },
  recon(m){
    let h = pageHead(m);
    h += `<div class="grid4">${[[`RM ${fmt(TENDER.totReq / 1e6, 2)} m`, 'Engineering-required value'], [`RM ${fmt(TENDER.totT / 1e6, 2)} m`, 'Tender value (reconciled items)'], [`${fmt((TENDER.totT / Math.max(TENDER.totReq, 1) - 1) * 100, 1)}%`, 'Overall variance'], [TENDER.gaps.length, 'Scope gaps']].map(([v, l]) => `<div class="kpi"><div class="v">${esc(v)}</div><div class="l">${esc(l)}</div></div>`).join('')}</div>`;
    h += `<div class="card" style="margin-top:12px"><h3>Scope gap engine</h3>${TENDER.gaps.length ? `<table class="t"><thead><tr><th>Scope area</th><th>BOQ items</th><th>Status</th></tr></thead><tbody>${TENDER.gaps.map(g => `<tr><td>${esc(g.name)}</td><td class="small">${esc(g.keys.join(', '))}</td><td>${badge(g.gap ? 'fail' : 'warn', g.gap ? 'MISSING' : 'PARTIAL')}</td></tr>`).join('')}</tbody></table>` : '<p>No scope gaps.</p>'}</div>`;
    h += `<div class="card"><h3>Reconciliation — required vs tender</h3><div class="row noprint" style="margin-bottom:6px"><button class="sm" data-act="csvrecon">Export (CSV)</button></div><div class="tw"><table class="t"><thead><tr><th>Item</th><th class="n">Required Qty</th><th class="n">Tender Qty</th><th class="n">Difference</th><th>Required Scope</th><th>Tender Scope</th><th class="n">Rate (tender)</th><th class="n">Rate (eng.)</th><th class="n">Variance (RM)</th><th>Issues</th></tr></thead><tbody>${TENDER.rows.map(r => `<tr><td>${esc(r.desc)} <span class="muted small">${esc(r.key)}</span></td><td class="n">${fmt(r.rq, 0)}</td><td class="n">${fmt(r.tq, 0)}</td><td class="n" style="color:${r.diff < 0 ? 'var(--ng)' : 'inherit'}">${fmt(r.diff, 0)}</td><td class="small">${esc(r.rscope)}</td><td class="small">${esc(r.tscope)}</td><td class="n">${fmt(r.trate, 2)}</td><td class="n">${fmt(r.erate, 2)}</td><td class="n">${fmt(r.variance, 0)}</td><td>${r.issues.map(i => badge(/Omitted|exclusion|Under|Duplication/.test(i) ? 'fail' : 'warn', i)).join(' ') || badge('pass', 'OK')}</td></tr>`).join('')}</tbody></table></div></div>`;
    h += `<div class="card"><h3>Contractor quotation (input)</h3>${editTable('tender', [{k:'key', l:'BOQ item', t:'sel', o:Object.keys(BOQ_LIB)}, {k:'_d', l:'Description', ro:true, fmt:(v, r) => esc((BOQ_LIB[r.key] || {}).desc || '')}, {k:'qty', l:'Tender qty', n:1}, {k:'rate', l:'Rate (RM)', n:1}, {k:'scope', l:'Tender scope / specification', w:200}, {k:'flag', l:'Flag', t:'sel', o:['','Provisional','Excluded','TBC']}], {perm:'tender', idx:1, tpl:{id:'', key:'EW_CUT', qty:0, rate:0, scope:'', flag:''}, extra:`<button class="sm" data-act="gentender">Regenerate demonstration quotation</button>`})}</div>`;
    return h;
  },
  techeval(m){
    const crit = [['method','Method statement / approach'],['programme','Programme'],['experience','Relevant experience'],['compliance','Technical compliance'],['qa','QA/QC & HSE']];
    P.teWeights = P.teWeights || {method:0, programme:0, experience:0, compliance:0, qa:0}; const W = P.teWeights, ws = sum(Object.values(W).map(Number));
    let h = pageHead(m) + `<div class="card"><h3>Technical evaluation matrix (score 1–5)</h3><div class="tw"><table class="t"><thead><tr><th>Criterion</th><th class="c">Weight</th>${(P.reg.techeval || []).map(b => `<th class="c">${esc(b.bidder)}</th>`).join('')}</tr></thead><tbody>`;
    crit.forEach(([k, l]) => h += `<tr><td>${esc(l)}</td><td><input class="num" data-num="1" data-bind="teWeights.${k}" value="${W[k]}" style="width:56px"${dis('tender')}></td>${(P.reg.techeval || []).map((b, i) => `<td><input class="num" data-num="1" data-bind="reg.techeval.${i}.score.${k}" value="${b.score[k]}" style="width:50px"${dis('tender')}></td>`).join('')}</tr>`);
    if (ws > 0) h += `<tr class="tot"><td>Weighted technical score</td><td class="c">${ws}</td>${(P.reg.techeval || []).map(b => `<td class="c">${fmt(sum(crit.map(([k]) => (+W[k] || 0) * (+b.score[k] || 0))) / ws, 2)}</td>`).join('')}</tr>`;
    h += `</tbody></table></div>${ws > 0 ? '' : '<p class="small"><b>No ranking is produced</b> until evaluation weights (decision criteria) are defined.</p>'}<p class="small muted">Commercial comparison: see Tender Reconciliation. Scope gaps for the reconciled bidder: ${TENDER.gaps.length}.</p>`;
    h += `<h4>Bidders</h4>${editTable('reg.techeval', [{k:'bidder', l:'Bidder'}], {perm:'tender', tpl:{bidder:'Bidder', score:{method:3, programme:3, experience:3, compliance:3, qa:3}}})}</div>`;
    return h;
  },
  clar(m){
    const auto = autoClarifications();
    return pageHead(m) + `<div class="card"><h3>Auto-generated clarifications (from reconciliation & scope gap engines)</h3><div class="tw"><table class="t"><thead><tr><th>Ref</th><th>Subject</th><th>Clarification</th><th>Category</th></tr></thead><tbody>${auto.map(c => `<tr><td>${esc(c.id)}</td><td class="small">${esc(c.ref)}</td><td>${esc(c.q)}</td><td>${badge('warn', c.cat)}</td></tr>`).join('')}</tbody></table></div></div>
      <div class="card"><h3>Clarification register (user)</h3>${editTable('reg.clarifications', [{k:'id', l:'Ref'}, {k:'ref', l:'Subject'}, {k:'q', l:'Clarification', t:'area', w:260}, {k:'cat', l:'Category'}, {k:'status', l:'Status', t:'sel', o:['Open','Issued','Answered','Closed']}, {k:'resp', l:'Bidder response', t:'area', w:200}], {tpl:{id:'TC-U', ref:'', q:'', cat:'', status:'Open', resp:''}})}</div>`;
  },
  risk(m){
    const grid = Array.from({length:5}, () => Array(5).fill(0)); RISKS.forEach(r => grid[5 - r.C][r.L - 1]++);
    return pageHead(m) + `<div class="grid2"><div class="card"><h3>Risk matrix (Likelihood × Consequence)</h3><table class="t" style="max-width:360px"><tbody>${grid.map((row, i) => `<tr><th>C${5 - i}</th>${row.map((v, j) => { const s = (5 - i) * (j + 1); return `<td class="c" style="background:${s >= 15 ? '#F2C9C7' : s >= 8 ? '#F8E3B5' : '#E6F1E8'};font-weight:700">${v || ''}</td>`; }).join('')}</tr>`).join('')}<tr><th></th>${[1,2,3,4,5].map(l => `<th class="c">L${l}</th>`).join('')}</tr></tbody></table></div>
      <div class="card"><h3>Summary</h3><p>${RISKS.length} risks: ${RISKS.filter(r => r.level === 'High').length} High, ${RISKS.filter(r => r.level === 'Medium').length} Medium, ${RISKS.filter(r => r.level === 'Low').length} Low. Automatic risks are triggered by calculation results and are re-evaluated on every change.</p></div></div>
      <div class="card"><h3>Design risk register — Technical issue → Construction → Cost → Programme</h3>${riskTable(RISKS)}</div>
      <div class="card"><h3>User-defined risks</h3>${editTable('reg.risks', [{k:'id', l:'ID'}, {k:'mod', l:'Module', t:'sel', o:MODULES.map(x => x.id)}, {k:'title', l:'Title', w:160}, {k:'issue', l:'Technical issue', t:'area'}, {k:'cons', l:'Construction consequence', t:'area'}, {k:'cost', l:'Cost consequence', t:'area'}, {k:'prog', l:'Programme consequence', t:'area'}, {k:'L', l:'L', n:1}, {k:'C', l:'C', n:1}, {k:'mit', l:'Mitigation', t:'area'}, {k:'owner', l:'Owner'}], {tpl:{id:'RK-U', mod:'m54', title:'', issue:'', cons:'', cost:'', prog:'', L:3, C:3, mit:'', owner:''}})}</div>`;
  },
  construct(m){
    return pageHead(m) + `<div class="card"><h3>Constructability review (auto-flagged from calculations)</h3><table class="t"><thead><tr><th>Aspect</th><th>Flag</th><th>Basis</th></tr></thead><tbody>${constructItems().map(c => `<tr><td>${esc(c.t)}</td><td>${badge(c.flag ? 'warn' : 'pass', c.flag ? 'REVIEW' : 'OK')}</td><td class="small">${esc(c.note)}</td></tr>`).join('')}</tbody></table>
      <div class="row" style="margin-top:8px"><input id="cnew" placeholder="Add constructability item (aspect)" style="max-width:280px"${dis('registers')}><button class="sm" data-act="addconstruct"${dis('registers')}>Add</button></div></div>`;
  },
  ve(m){
    return pageHead(m) + `<div class="card"><h3>Value engineering options (costed with current BOQ rates)</h3><table class="t"><thead><tr><th>ID</th><th>Option</th><th class="n">Base (RM)</th><th class="n">Alternative (RM)</th><th class="n">Saving (RM)</th><th>Engineering note</th><th>Decision</th></tr></thead><tbody>${P.ve.map((v, i) => { const d = VE_DEFAULT.find(x => x.id === v.id) || v; const b = veCost(d, 'base'), a = veCost(d, 'alt'); return `<tr><td>${esc(v.id)}</td><td>${esc(d.title)}</td><td class="n">${fmt(b, 0)}</td><td class="n">${fmt(a, 0)}</td><td class="n"><b>${fmt(b - a, 0)}</b></td><td class="small">${esc(d.note)}</td><td><select data-bind="ve.${i}.accept"${dis('approve')}>${['','Accepted','Rejected','Further study'].map(o => `<option${o === v.accept ? ' selected' : ''}>${o}</option>`).join('')}</select></td></tr>`; }).join('')}</tbody></table><p class="small muted">Options are not adopted automatically — decision by PE / client.</p></div>`;
  },
  authority(m){
    let h = pageHead(m) + `<div class="card"><h3>Authority compliance matrix</h3><div class="tw"><table class="t"><thead><tr><th>Authority</th><th>Requirement / submission</th><th>Stage</th><th>Reference</th><th>Status</th><th>Responsible</th></tr></thead><tbody>`;
    AUTH_ROWS.forEach((r, i) => { if (r[4] && r[4] !== P.type) return; const a = P.authority['A' + i] = P.authority['A' + i] || {status:'Not started', resp:''};
      h += `<tr><td><b>${esc(r[0])}</b></td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td class="small">${esc(r[3])}</td><td><select data-bind="authority.A${i}.status"${dis('registers')}>${['Not started','In preparation','Submitted','Approved','Conditional','Rejected','N/A'].map(o => `<option${o === a.status ? ' selected' : ''}>${o}</option>`).join('')}</select></td><td><input data-bind="authority.A${i}.resp" value="${esc(a.resp || '')}"${dis('registers')}></td></tr>`; });
    h += `</tbody></table></div></div><div class="card"><h3>PBT requirements — ${esc(pbtName())}</h3><p class="small">Project-specific PBT identified from state / district. Requirements must be obtained from the PBT; entries below are placeholders for confirmed information.</p><table class="t"><thead><tr><th>Requirement</th><th>Confirmed information</th><th>Status</th></tr></thead><tbody>`;
    P.pbtReq = P.pbtReq || {};
    PBT_FIELDS.forEach((f, i) => { const v = P.pbtReq[i] = P.pbtReq[i] || {text:'', st:'AUTHORITY CONFIRMATION REQUIRED'}; h += `<tr><td>${esc(f)}</td><td><input data-bind="pbtReq.${i}.text" value="${esc(v.text)}"${dis('registers')}></td><td><select data-bind="pbtReq.${i}.st"${dis('registers')}>${['AUTHORITY CONFIRMATION REQUIRED','Confirmed','Not applicable'].map(o => `<option${o === v.st ? ' selected' : ''}>${o}</option>`).join('')}</select></td></tr>`; });
    return h + '</tbody></table></div>';
  },
  standards(m){
    let h = pageHead(m) + `<div class="card"><p class="small">Every reference carries issuing authority, title, number, edition, revision, effective date, URL, last verification date and status (CURRENT / VERIFY / SUPERSEDED / REFERENCE ONLY). <b>Clauses are not cited unless confirmed — ${CVR}.</b> Entries default to VERIFY until checked against the issuing authority.</p></div>`;
    STD_GROUPS.forEach(g => { const idx = P.standards.map((s, i) => [s, i]).filter(([s]) => s.group === g); if (!idx.length) return;
      h += `<div class="card"><h3>${esc(g)}</h3><div class="tw"><table class="t"><thead><tr><th>Ref</th><th>Authority</th><th style="min-width:220px">Title</th><th>No.</th><th>Edition</th><th>Rev</th><th>Effective</th><th>URL</th><th>Clause</th><th>Verified (date)</th><th>Status</th></tr></thead><tbody>${idx.map(([s, i]) => `<tr><td>${esc(s.id)}</td><td class="small">${esc(s.auth)}</td><td>${esc(s.title)}<div class="small muted">${esc(s.scope)}</div></td><td><input data-bind="standards.${i}.number" value="${esc(s.number)}"${dis('registers')}></td><td><input data-bind="standards.${i}.edition" value="${esc(s.edition)}"${dis('registers')}></td><td><input data-bind="standards.${i}.rev" value="${esc(s.rev)}" style="width:50px"${dis('registers')}></td><td><input data-bind="standards.${i}.date" value="${esc(s.date)}" style="width:70px"${dis('registers')}></td><td class="small">${s.url ? `<a href="${esc(s.url)}" target="_blank" rel="noopener">link</a>` : '—'}</td><td class="small" style="color:var(--wn)">${esc(s.clause)}</td><td><input data-bind="standards.${i}.verified" value="${esc(s.verified)}" placeholder="YYYY-MM-DD" style="width:92px"${dis('registers')}></td><td><select data-bind="standards.${i}.status"${dis('registers')}>${STD_STATUS.map(o => `<option${o === s.status ? ' selected' : ''}>${o}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div></div>`; });
    h += `<div class="card"><h3>MSMA reference mapping (MSMA as a system of requirements)</h3><table class="t"><thead><tr><th>Topic</th><th>Source</th><th>Requirement</th><th>Applied in</th><th>Note</th></tr></thead><tbody>${MSMA_MAP.map(r => `<tr>${r.map(c => `<td class="small">${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
    h += `<div class="card"><h3>Design criteria conflict</h3>${criteriaConflict()}</div>`;
    return h;
  },
  assume(m){
    const a = autoAssumptions();
    return pageHead(m) + `<div class="card"><h3>Automatic register — method assumptions and non-verified inputs (${a.length})</h3><div class="tw" style="max-height:520px;overflow:auto"><table class="t"><thead><tr><th>Source</th><th>Assumption</th><th>Type</th></tr></thead><tbody>${a.map(x => `<tr><td class="muted">${esc(x.src)}</td><td>${esc(x.text)}</td><td>${badge(x.type === 'Unknown' ? 'fail' : x.type === 'Estimated' ? 'warn' : 'na', x.type)}</td></tr>`).join('')}</tbody></table></div></div>
      <div class="card"><h3>User assumptions</h3>${editTable('reg.assumptions', [{k:'mod', l:'Module', t:'sel', o:MODULES.map(x => x.id)}, {k:'text', l:'Assumption', t:'area', w:340}, {k:'type', l:'Type', t:'sel', o:['Consultant Assumption','Client instruction','Estimated']}, {k:'status', l:'Status', t:'sel', o:['Open','Confirmed','Superseded']}], {tpl:{mod:'m2', text:'', type:'Consultant Assumption', status:'Open'}})}</div>`;
  },
  eq(m){ return pageHead(m) + `<div class="card">${editTable('reg.queries', [{k:'id', l:'ID'}, {k:'to', l:'To'}, {k:'subject', l:'Subject', t:'area', w:260}, {k:'raised', l:'Raised'}, {k:'status', l:'Status', t:'sel', o:['Open','Answered','Closed']}, {k:'response', l:'Response', t:'area', w:220}], {tpl:{id:'EQ-', to:'', subject:'', raised:today(), status:'Open', response:''}})}</div>`; },
  drawings(m){ return pageHead(m) + `<div class="card"><p class="small">Required drawings are generated from the project type; BESS drawings are included for Type B only.</p>${editTable('reg.drawings', [{k:'no', l:'Drawing no.'}, {k:'title', l:'Title', w:260}, {k:'disc', l:'Discipline'}, {k:'rev', l:'Rev'}, {k:'status', l:'Status', t:'sel', o:['Required','In progress','Issued for review','Issued for tender','IFC','Not required']}, {k:'resp', l:'Responsible'}], {tpl:{no:'', title:'', disc:'', rev:'-', status:'Required', resp:''}})}</div>`; },
  reports(m){ return pageHead(m) + `<div class="card">${editTable('reg.reports', [{k:'no', l:'Report no.'}, {k:'title', l:'Title', w:260}, {k:'rev', l:'Rev'}, {k:'date', l:'Date'}, {k:'status', l:'Status', t:'sel', o:['Draft','Issued for comment','Issued','Superseded']}, {k:'by', l:'By'}], {tpl:{no:'RPT-', title:'', rev:'P0', date:today(), status:'Draft', by:P.user}})}</div>
    <div class="card"><h3>Project revision history</h3><table class="t"><thead><tr><th>Rev</th><th>Date</th><th>Description</th><th>By</th></tr></thead><tbody>${P.revisions.map(r => `<tr><td>${esc(r.rev)}</td><td>${esc(r.date)}</td><td>${esc(r.desc)}</td><td>${esc(r.by)}</td></tr>`).join('')}</tbody></table>${can('approve') ? `<div class="row" style="margin-top:8px"><input id="revdesc" placeholder="Revision description" style="max-width:320px"><button class="sm" data-act="projrev">Issue project revision (snapshot)</button></div>` : ''}</div>
    <div class="card"><h3>Audit trail (latest 60 changes — never overwritten silently)</h3><table class="t"><thead><tr><th>Time</th><th>User / role</th><th>Action</th><th>Detail</th></tr></thead><tbody>${P.audit.slice(0, 60).map(a => `<tr><td class="small">${esc(a.t.replace('T', ' ').slice(0, 19))}</td><td class="small">${esc(a.user)} (${esc(a.role)})</td><td>${esc(a.action)}</td><td class="small">${esc(a.detail)}</td></tr>`).join('')}</tbody></table></div>`; },
  deliv(m){ return pageHead(m) + `<div class="card">${editTable('reg.deliverables', [{k:'title', l:'Deliverable', w:260}, {k:'stage', l:'Stage'}, {k:'status', l:'Status', t:'sel', o:['Not started','In progress','Issued','Approved']}, {k:'due', l:'Due'}, {k:'resp', l:'Responsible'}], {tpl:{title:'', stage:'Tender', status:'Not started', due:'', resp:''}})}</div>`; },
  review(m){
    const ids = Object.keys(R), fails = ids.filter(i => R[i].status === 'fail'), mi = missingInfo(), ver = P.standards.filter(s => s.status === 'VERIFY').length, hi = RISKS.filter(r => r.level === 'High');
    const unconf = (P.criteria || []).filter(c => c.eng !== 'Confirmed').length, notIssued = ids.filter(i => !(P.calcMeta[i] || {}).issued).length;
    const gates = [
      ['All applicable calculations executed', ids.length > 0, `${ids.length} calculations`],
      ['No unresolved engineering non-compliance', !fails.length, fails.map(i => CALCS[i].no).join(', ') || 'None'],
      ['Outstanding information closed', !Object.keys(mi.tags).length && !mi.docs.length, `${Object.values(mi.tags).reduce((a, b) => a + b.length, 0)} warnings, ${mi.docs.length} documents`],
      ['Tender scope gaps resolved', !TENDER.gaps.length, TENDER.gaps.map(g => g.name).join(', ') || 'None'],
      ['High risks mitigated / accepted', !hi.length, hi.map(r => r.id).join(', ') || 'None'],
      ['Standards verified (no VERIFY status)', !ver, `${ver} references with VERIFY status`],
      ['Design criteria conflicts confirmed by Engineer', !unconf, `${unconf} criteria pending`],
      ['Calculations issued with revision', !notIssued, `${notIssued} calculations not issued`],
    ];
    const ok = gates.filter(g => g[1]).length;
    let h = pageHead(m) + `<div class="card"><h3>Tender review gates <span class="badge ${ok === gates.length ? 'pass' : 'warn'}">${ok}/${gates.length}</span></h3><table class="t"><thead><tr><th>Gate</th><th>Status</th><th>Evidence</th></tr></thead><tbody>${gates.map(g => `<tr><td>${esc(g[0])}</td><td>${badge(g[1] ? 'pass' : 'fail', g[1] ? 'CLEARED' : 'OPEN')}</td><td class="small">${esc(g[2])}</td></tr>`).join('')}</tbody></table></div>`;
    P.review.sign = P.review.sign || {prepared:'', checked:'', approved:''};
    h += `<div class="card"><h3>Sign-off</h3><div class="grid3">${[['prepared','Prepared (Design / Tender Engineer)','edit'], ['checked','Checked (Checker)','check'], ['approved','Approved (PE / PEPC)','approve']].map(([k, l, perm]) => `<div><label class="small muted">${l}</label><input data-bind="review.sign.${k}" value="${esc(P.review.sign[k])}"${dis(perm)} placeholder="Name / date"></div>`).join('')}</div><p class="small muted">Sign-off fields are role-restricted. Approval does not clear open gates automatically.</p>
      <h4>Reviewer comments</h4><textarea data-bind="review.comments"${dis('check')} rows="4">${esc(P.review.comments || '')}</textarea></div>`;
    return h;
  },
  report(m){
    P.repOpt = P.repOpt || {calcSheets: true, appendices: true};
    let h = `<div class="noprint">${pageHead(m)}</div>` + `<div class="card noprint"><div class="row"><label><input type="checkbox" style="width:auto" data-bind="repOpt.appendices" data-bool="1" ${P.repOpt.appendices ? 'checked' : ''}> Appendices</label><label><input type="checkbox" style="width:auto" data-bind="repOpt.calcSheets" data-bool="1" ${P.repOpt.calcSheets ? 'checked' : ''}> Full calculation sheets</label><span class="sp" style="flex:1"></span>
      <button class="pri" data-act="print">Print / Save as PDF (A4)</button><button data-act="docx">Download Word (.docx)</button><button data-act="htmlrep">Download HTML</button></div>
      <p class="small muted">A4 portrait · margins L 25 mm, R/T/B 20 mm · Aptos 11 pt body, 1.5 line spacing, justified, 6 pt after · headings 15/13/11 pt bold · tables 9–10 pt single spacing · calculations 10–11 pt single, left aligned. In Word, update fields (F9) to populate the table of contents and lists of figures/tables.</p></div>`;
    h += `<div class="noprint">${coverPanel()}${allAttachPanel()}</div>`;
    const chs = reportChapters();
    h += `<div class="card noprint"><h3>Download a single section</h3><p class="small muted">Each section is issued as its own document: a cover page for that section, document control, contents, the section itself (renumbered 1.0) and, for technical sections, its calculation sheets. Headers, footers and "Page X of Y" are included in Word and in Print / PDF.</p>
      <div class="row"><select id="secsel" style="max-width:420px">${chs.map(c => `<option value="${esc(properTitle(c.title))}">${esc(c.num)}  ${esc(c.title)}</option>`).join('')}</select>
      <label class="small"><input type="checkbox" id="seccalc" style="width:auto" checked> Include calculation sheets</label>
      <button class="sm" data-act="secpreview">Preview</button><button class="sm pri" data-act="secprint">Print / Save as PDF</button><button class="sm" data-act="secdocx">Word (.docx)</button><button class="sm" data-act="sechtml">HTML</button></div></div>`;
    h += `<div class="rep-wrap">${reportHTML(P.repOpt)}</div>`;
    return h;
  },
};
